import React from "react"
import Head from 'next/head'
import Point from "../Point/Point"
import styles from './Home.module.css'

import { HOME_TABS, FOOTER_TABS } from "../../constants";
import {  Header, Footer } from "../../components";
import Hello from "../Hello/Hello";

const Home: React.FC = () => {

  const hometabs = HOME_TABS;
  const footertabs = FOOTER_TABS;

  return (
    <>
      <Head>
        <title>Gandalf</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header tabs={hometabs} />
      
      <main className={styles.main}>
        <div className={styles.tabs}>
          {/* <Point /> */}
          <Hello />
        </div>
      </main>

      <Footer tabs={footertabs} />
    </>
  );
};

export default Home;
