import React, { ReactNode } from "react"
import Head from 'next/head'
import styles from './Home.module.css'

import { HOME_TABS, FOOTER_TABS } from "../../constants";
import {  Header, Footer } from "../../components";

type HomeProps = {
  children: React.ReactNode
}

const Home = ({ children }: HomeProps) => {

  const hometabs = HOME_TABS;
  const footertabs = FOOTER_TABS;

  return (
    <>
      <Head>
        <title>Gandalf</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header tabs={hometabs} />
      
      <main className={styles.main}>
        <div className={styles.tabs}>
          {children}
        </div>
      </main>

      <Footer tabs={footertabs} />
    </>
  );
};

export default Home;
